# Generated by Django 4.0.1 on 2022-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hacamat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='hacamat/')),
                ('ilkaciklama', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OzonTedavisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='ozon/')),
                ('ilkaciklama', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrpTedavisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='prp/')),
                ('ilkaciklama', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SulukTedavisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='suluk/')),
                ('ilkaciklama', models.TextField()),
            ],
        ),
    ]
