# Generated by Django 4.0.1 on 2022-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_hacamat_slug_ozontedavisi_slug_prptedavisi_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacamat',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ozontedavisi',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='prptedavisi',
            name='slug',
            field=models.SlugField(blank=True, default=2, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suluktedavisi',
            name='slug',
            field=models.SlugField(blank=True, default=2, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
