# Generated by Django 4.0.1 on 2022-03-01 13:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs')),
                ('title', models.CharField(max_length=100)),
                ('descriptionbaslik', models.TextField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('yazar', models.CharField(max_length=30)),
                ('tarih', models.DateField(auto_now_add=True)),
                ('zaman', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.category')),
            ],
        ),
    ]
