# Generated by Django 4.0.1 on 2022-03-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogs_yazar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='category',
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ManyToManyField(to='blogs.Category'),
        ),
    ]
