# Generated by Django 4.0.1 on 2022-12-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_rename_tarih_blogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='seodescription',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='seotitle',
            field=models.TextField(max_length=60, null=True),
        ),
    ]
